### ISSUE TITLE
Error with controllers

### ISSUE THREAD

**Issue by HB-Liang** [TopHillRobotics/quadruped-robot#35]
Big Thanks for getting this project open source!
I got started following the guide on https://quadruped-robot-docs.readthedocs.io/en/main/overview.html
When I tried to run that helloworld demo,
it launched without any errors 
but the problem occurs when I run the demo using "rosrun demo demo_helloworld sim"
which is shown in the screenshot. Could you tell what I've got wrong? Thanks
![2022-10-23 20-18-21 的屏幕截图](https://user-images.githubusercontent.com/114042103/197391616-77c7fd54-1fd6-47aa-9083-3cea76d34c20.png)

**Comment by TopHillRobotics** [comment]
We didn't have the problem you mentioned. Could you please tell us more details?

**Comment by HB-Liang** [comment]
Sorry for replying so late. Actually I don't know which message I can tell for fixing this problem. It's weird with controller spawner loaded controller with name "joint_state_controller" but the switch service didn't find this name. I reduced this problem with changing the reset function to ResetRobotByService, and helloworld demo works fine.
