### ISSUE TITLE
关于腿的运动学和jacobian计算

### ISSUE THREAD

**Issue by P1terQ** [TopHillRobotics/quadruped-robot#38]
感谢开源，在学习代码的过程中遇见了问题。请问qr_robot_config.cpp中关于3DoF腿的正逆运动学解算还有Jacobian的计算有相关参考资料或者推导过程吗？不清楚为什么是这个形式的

**Comment by P1terQ** [comment]
还有，请问为什么不同模式下的com_offset不同，这个正常情况下应该是0吧

**Comment by ZhenyuXu-ECNU** [comment]
关于腿的结算使用的是几何法，每条腿分别使用三角关系考虑从hip关节到末端的正逆运动学。另外，由于Force Balence方法将整个四足机器人看作是一个刚体，CoM的位置和转动惯量实际上是变动的。这个参数需要根据实际的运行效果单独调试
